WoltLab/com.woltlab.wcf.conversation

language/de.xml

Unified phrases they now looks like the other conversation dropdown menu items like close or assign labels.

Unified phrases

---

language/de.xml
language/en.xml

Adjusted phrases from the dialog to the inline dropdown menu.

Unified phrases (2)

---

templates/conversationList.tpl

The navigation has always content.

remove "hascontent"

---

language/en.xml

Reference thread:
https://community.woltlab.com/thread/247949-ready-grammar-use-punctuation-conversation-related-user-group-rebuild-data/

Bug fixes, better English grammar, punctuation, etc

---

files/lib/data/conversation/FeedConversation.class.php
templates/conversationList.tpl

See https://github.com/WoltLab/WCF/pull/2075.

Remove obsolete parameter 'appendSession' from LinkHandler calls

---

language/en.xml

@BurntimeX I believe these can be merged, infractions and moderatedusergroup lang pull requests. Just not WCF and burning board ones yet.. I still have gallery, blog, calendar, filebase main products to knock out too.

latest conversations phrase adjustments, etc

---

files/js/WoltLabSuite/Core/Conversation/Ui/Subject/Editor.js
templates/conversationLabelAssignment.tpl
templates/conversationLeave.tpl

Enforces an unified appearance of conversation related dialogs.

Unify dialog appearance

---

files/lib/page/ConversationListPage.class.php
templates/conversationList.tpl

Exclude invisible participants from conversations started by other users

---

files/lib/data/conversation/Conversation.class.php
files/lib/data/conversation/message/ConversationMessage.class.php
files/lib/data/conversation/message/ConversationMessageAction.class.php
language/de.xml
language/en.xml
userGroupOption.xml

Read only mode

---

files/lib/data/conversation/ConversationAction.class.php
files/lib/form/ConversationAddForm.class.php
language/de.xml
language/en.xml

Validate adding groups to conversations

---

userGroupOption.xml

Support for WebP images

---

files/lib/form/ConversationDraftEditForm.class.php

Use a simple query here to prevent creating metric tons of useless objects.
see #146

Replace use of deprecated UserProfile::getUserProfiles()

---

files/lib/system/worker/ConversationRebuildDataWorker.class.php

Delete conversations without messages in `ConversationRebuildDataWorker`

---

files/js/WCF.Conversation.js
files/js/WoltLabSuite/Core/Conversation/Ui/Message/Quote.js
templates/conversation.tpl
ts/WoltLabSuite/Core/Conversation/Ui/Message/Quote.ts

Use `Ui/Message/Quote` instead of `WCF.Conversation.Message.QuoteHandler`

---

files/lib/data/conversation/ConversationAction.class.php

see WoltLab/com.woltlab.wbb#455

Refactor logic in ConversationAction::markAsRead()

---

files/acp/update_com.woltlab.wcf.conversation_5.5_cleanup_orphaned_attachments.php
package.xml

Clean up orphaned attachments when upgrading to 5.5

---

files/lib/form/ConversationDraftEditForm.class.php

Sending a draft with multiple messages messed up the order

---

language/de.xml
language/en.xml

The list of phrases was generated with this (simple) script:
#!/bin/bash
if [ -z "$1" ]
then
echo "$0 <language_code>" >&2
exit 1
fi
lang="$1"
comm -23 <(
for file in "$lang.xml" "language/$lang.xml"
do
for rev in $(git rev-list --all -- "$file")
do
git show $rev:$file
done
done |awk -F'"' '/item name/{print $2}' |sort -u
) <(
cat "language/$lang.xml" |awk -F'"' '/item name/{print $2}' |sort -u
) |sed 's!^!<item name="!;s!$!"/>!'

Update list of deleted phrases

---

files/style/conversation.scss
templates/conversationList.tpl

ref https://www.woltlab.com/community/thread/300413-conversation-quota/

Use meter tag to show conversation quota usage

---

files/lib/data/conversation/ConversationAction.class.php
files/lib/page/ConversationPage.class.php

https://www.woltlab.com/community/thread/301779-konversation-mit-bcc-leakt-teilnehmer/

Properly suppress modification log entries for invisible participants

---

templates/conversation.tpl
templates/conversationAdd.tpl
templates/conversationMessageInlineEditor.tpl
templates/conversationQuickReply.tpl

See https://github.com/WoltLab/WCF/pull/5779

Shared template group

---

.php-cs-fixer.dist.php
files/lib/data/conversation/Conversation.class.php
files/lib/data/conversation/ConversationAction.class.php
files/lib/data/conversation/FeedConversation.class.php
files/lib/data/conversation/FeedConversationList.class.php
files/lib/data/conversation/UserConversationList.class.php
files/lib/page/ConversationFeedPage.class.php
files/lib/page/ConversationRssFeedPage.class.php
files/lib/system/cache/runtime/ConversationMessageRuntimeCache.class.php
templates/conversationList.tpl

See https://github.com/WoltLab/WCF/pull/5790

Make use of the new API for the conversation feed

---

files/lib/data/conversation/message/ConversationMessageAction.class.php
templates/conversationMessageInlineEditor.tpl

See https://github.com/WoltLab/WCF/pull/5787

Using html upcast

---

files/js/WoltLabSuite/Core/Conversation/Ui/User/Menu/Data/Conversation.js
package-lock.json
package.json
ts/WoltLabSuite/Core/Conversation/Ui/User/Menu/Data/Conversation.ts

See https://github.com/WoltLab/WCF/pull/5837

Event to update the counter in user menu

---

files/lib/data/conversation/message/ConversationMessageAction.class.php

See https://www.woltlab.com/community/thread/307842-zitierte-bilddatei/

Load embedded content for the quote message

---

files/lib/data/conversation/message/ConversationMessage.class.php
files/lib/data/conversation/message/ConversationMessageAction.class.php

See https://www.woltlab.com/community/thread/308180-text-der-inhalt-kann-nicht-angezeigt-werden-da-er-nicht-mehr-verfügbar-ist-in-be/

Load embedded content before the email text is processed
